# theme.toml template for a Hugo theme
# See https://github.com/gohugoiox/hugoThemes#themetoml for an example

name = "PaulHofmann"
#license = ""
#licenselink = ""
#description = ""
#homepage = ""
#demosite = ""
#tags = ["", ""]
#features = ["", """]
#min_version = "0.1.0"

[author]
  name = "Paul Hofmann"
  homepage = "https://www.paulhofmann.dev"
